[스택, 큐, 덱] 9월 14일
Altu-Bitu-3/Altu-Bitu-Youjin-Kim pull request #5
Opened 2022-09-14 12:42 UTC by RaseBerrie

#### 내용&질문
> 제출합니다!

#### <기존 제출>
> 11866, 18115

2022-09-15 08:32 UTC, bsa0322 requested changes
**p1. 18115 코드리뷰 완료**
유진님 안녕하세요 😊 코드를 깔끔히 너무 잘 짜주셔서 잘 읽었습니다! 다음엔 주석도 있으면 더 좋을 것 같아요 🥰 p1 코멘트는 꼭 수정 부탁드립니다! 수고하셨습니다 ✨❤

2022-09-15 08:32 UTC, bsa0322 commented on 09월 09일 - 스택, 큐, 덱/18115.cpp
> +
p3. result에 우선 1을 넣고 시작해줬네요~! 해당 방법도 좋지만, 어차피 다른 연산들과 동일하게 적용할 수 있으니 26번째 줄의 for문에서 같이 처리해도 좋을 것 같아요~!

2022-09-15 08:32 UTC, bsa0322 commented on 09월 09일 - 스택, 큐, 덱/18115.cpp
> +    }
기술을 거꾸로 쓰기 위해 stack을 활용해 주셨네요! 아주 좋습니다 👍👍👍

2022-09-15 08:32 UTC, bsa0322 commented on 09월 09일 - 스택, 큐, 덱/18115.cpp
> +    }
p1. 현재 2번째 기술에 대해서 insert연산을 수행해주셨는데 insert의 시간복잡도는 O(N)이 걸려요! deque의 특성을 활용해서 시간복잡도 O(1)으로 해당 부분을 해결할 수 있을 것 같습니다! 🥰

p2. 해당 부분은 문제의 핵심 연산이니 함수화를 하면 가독성을 더 높일 수 있을 것 같습니다! 특히, **코딩테스트에선 solution 타입이 대부분으로, main함수가 제공되지 않고 solution함수만 제공되어 정답을 리턴**하는 형태이니 지금부터 함수화에 익숙해지시면 좋을 것 같아요! 🔥

2022-09-15 14:06 UTC, jk0527 requested changes
P1. 11866 코드 리뷰 완료

이 문제는 queue와 deque 중 하나만 사용해서 풀 수 있어요! 그리고 값은 vector에 저장한 후에 출력하시면 됩니다! 지금 코드가 돌아가기는 하지만 불필요한 자료구조가 사용된 것 같아서 코멘트 드린 부분 수정해주시면 좋을 것 같습니다! 연산에 사용하는 로직은 좋습니다!!😎😎 수정하시고 리뷰어 호출해주세요!

2022-09-15 14:06 UTC, jk0527 commented on 09월 09일 - 스택, 큐, 덱/11866.cpp
> +    queue <int> sorted;
원을 구현할 수 있다면 이 문제를 풀 수 있을 것 같아요. 원을 만들어서 맨 앞에서 빼고 맨 뒤에 추가하는 방법으로 문제를 풀면 되니까요! 그러면 deque와 queue 둘 다 필요할 것 같지는 않아요..! 하나만 사용하면 될 것 같은데 어떤 걸 사용하는 것이 좋을까요? 그리고 지금 sorted queue는 그냥 vector로 구현해도 될 것 같아요!

2022-09-15 14:06 UTC, jk0527 commented on 09월 09일 - 스택, 큐, 덱/11866.cpp
> +    while (joseph.empty() == false) {
!joseph.empty() 이렇게 조건 넣으셔도 돼요! 그리고 여기서부터 30번째 줄까지는 연산이니까 함수화해도 좋을 것 같아요!

2022-09-15 14:06 UTC, jk0527 commented on 09월 09일 - 스택, 큐, 덱/11866.cpp
> +            joseph.push_back(temp);
tmp에 저장하지 않고 바로 joseph.front()를 push해도 될 것 같아요!

2022-09-20 04:38 UTC, RaseBerrie commented on 09월 09일 - 스택, 큐, 덱/18115.cpp
> +    }
> p2. 해당 부분은 문제의 핵심 연산이니 함수화를 하면 가독성을 더 높일 수 있을 것 같습니다! 특히, **코딩테스트에선 solution 타입이 대부분으로, main함수가 제공되지 않고 solution함수만 제공되어 정답을 리턴**하는 형태이니 지금부터 함수화에 익숙해지시면 좋을 것 같아요! 🔥

처음에는 해당 부분을 함수화해서 돌리는 형태였는데, 시간 초과 에러 때문에 main 안으로  다시 집어넣게 되었습니다. p1에서 언급해 주신 문제 때문인 것 같은데, 사실 deque의 특성... 활용... 생각해 봤지만 어렵네요. 혹시 힌트를 조금만 더 주실 수 있을까요?

2022-09-20 04:45 UTC, RaseBerrie commented on 09월 09일 - 스택, 큐, 덱/11866.cpp
> +    queue <int> sorted;
혹시 자료구조를 여러 종류 사용해서 문제를 풀이하면 일반적으로 코딩 테스트에서 점수가 깎이게 되나요? 저는 각각의 역할에 특화된 구조를 사용할 목적으로 최대한 여러 자료구조를 이용하고 있었는데, 만약 감점 사유가 된다면 앞으로도 그 점을 참고해 풀이하고자 합니다.

2022-09-20 06:48 UTC, jk0527 commented on 09월 09일 - 스택, 큐, 덱/11866.cpp
> +    queue <int> sorted;
메모리 초과가 나지 않는다면 자료구조를 많이 사용한다고 해서 점수가 감점되지는 않을 거예요! 제가 말씀드리고 싶었던 부분은 이 문제는 queue와 vector만 이용해서 해결이 가능하다는 것입니다..! deque은 front와 back 모두 원소를 추가하거나 제가하는 것이 필요한 경우에 사용하는 자료구조입니다. 이 문제에서는 양쪽에 추가/제거할 일이 없기 때문에 더 간단한 queue를 이용하시면 돼요!!

그리로 queue의 연산이 필요없는 경우에는 더 간단한 vector를 사용하시면 되고요! 코드는 간단하고 이해하기 쉬울수록 좋으니까요!! 자료구조를 기능에 맞게 적절하게 사용하시면 됩니다! 😎😎

2022-09-21 13:15 UTC, RaseBerrie commented on 09월 09일 - 스택, 큐, 덱/11866.cpp
> +    queue <int> sorted;
설명 정말 감사드립니다! 조언해 주신 대로 queue만 사용하는 방향으로 수정했습니다. 사용할 수 있는 가장 간단한 구조를 사용할 것을 기억해 둘게요. 🥰

2022-09-22 01:01 UTC, jk0527 commented on 09월 09일 - 스택, 큐, 덱/11866.cpp
> +    queue <int> sorted;
P3.
네 수정하신 코드 좋습니다!! 11866은 이대로 머지하셔도 될 것 같아요!!😎

2022-09-22 01:01 UTC, jk0527 approved these changes

2022-09-24 06:30 UTC, merged